# Initialization

In [1]:
import logging

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
%matplotlib inline
%config InlineBackend.figure_format = 'png'
%config InlineBackend.figure_format = 'retina'

# Загрузка данных

In [3]:
items = pd.read_parquet("items.par")
events = pd.read_parquet("events.par")

# Разбиение с учётом хронологии

Рекомендательные системы на практике работают с учётом хронологии. Поэтому поток событий для тренировки и валидации полезно делить на то, что уже случилось, и что ещё случится. Это позволяет проводить валидацию на тех же пользователях, на которых тренировались, но на их событиях в будущем.

# === Знакомство: "холодный" старт

In [4]:
# зададим точку разбиения
train_test_global_time_split_date = pd.to_datetime("2017-08-01").date()

train_test_global_time_split_idx = events["started_at"] < train_test_global_time_split_date
events_train = events[train_test_global_time_split_idx]
events_test = events[~train_test_global_time_split_idx]

# количество пользователей в train и test
users_train = events_train["user_id"].drop_duplicates()
users_test = events_test["user_id"].drop_duplicates()
# количество пользователей, которые есть и в train, и в test
common_users  = set(users_train).intersection(set(users_test))

print(len(users_train), len(users_test), len(common_users))

428220 123223 120858

In [5]:
cold_users = set(users_test) - set(users_train)

print(len(cold_users))

2365

# === Знакомство: первые персональные рекомендации

In [6]:
from sklearn.preprocessing import MinMaxScaler

top_pop_start_date = pd.to_datetime("2015-01-01").date()

item_popularity = events_train \
    .query("started_at >= @top_pop_start_date") \
    .groupby(["item_id"]).agg(users=("user_id", "nunique"), avg_rating=("rating", "mean")).reset_index()

# нормализация пользователей и среднего рейтинга, требуется для их приведения к одному масштабу
scaler = MinMaxScaler()
item_popularity[["users_norm", "avg_rating_norm"]] = scaler.fit_transform(
    item_popularity[["users", "avg_rating"]]
)

# вычисляем popularity_score, как скор популярности со штрафом за низкий рейтинг
item_popularity["popularity_score"] = (
    item_popularity["users_norm"] * item_popularity["avg_rating_norm"]
)

# сортируем по убыванию popularity_score
item_popularity = item_popularity.sort_values(by = 'popularity_score', ascending = False)

# выбираем первые 100 айтемов со средней оценкой avg_rating не меньше 4
top_k_pop_items = item_popularity[item_popularity['avg_rating'] > 4].head(100)

In [7]:
top_k_pop_items.head()

,item_id,users,avg_rating,users_norm,avg_rating_norm,popularity_score
32387,18007564,20207,4.321275,0.496596,0.830319,0.412333
32623,18143977,19462,4.290669,0.478287,0.822667,0.393471
2,3,15139,4.706057,0.372042,0.926514,0.344702
30695,16096824,16770,4.301014,0.412126,0.825253,0.340108
1916,15881,13043,4.632447,0.320529,0.908112,0.291076

In [10]:
# добавляем информацию о книгах
top_k_pop_items = top_k_pop_items.merge(
    items.set_index("item_id")[["author", "title", "genre_and_votes", "publication_year"]], on="item_id")

with pd.option_context('display.max_rows', 10):
    display(top_k_pop_items[["item_id", "author", "title", "publication_year", "users", "avg_rating", "popularity_score", "genre_and_votes"]])

,item_id,author,title,publication_year,users,avg_rating,popularity_score,genre_and_votes
0,18007564,Andy Weir,The Martian,2014,20207,4.321275,0.412333,"{'Science Fiction': 11966, 'Fiction': 8430}"
1,18143977,Anthony Doerr,All the Light We Cannot See,2014,19462,4.290669,0.393471,"{'Historical-Historical Fiction': 13679, 'Fict..."
2,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,1997,15139,4.706057,0.344702,"{'Fantasy': 59818, 'Fiction': 17918, 'Young Ad..."
3,16096824,Sarah J. Maas,A Court of Thorns and Roses (A Court of Thorns...,2015,16770,4.301014,0.340108,"{'Fantasy': 14326, 'Young Adult': 4662, 'Roman..."
4,15881,"J.K. Rowling, Mary GrandPré",Harry Potter and the Chamber of Secrets (Harry...,1999,13043,4.632447,0.291076,"{'Fantasy': 50130, 'Young Adult': 15202, 'Fict..."
...,...,...,...,...,...,...,...,...
95,8490112,Laini Taylor,Daughter of Smoke & Bone (Daughter of Smoke & ...,2011,4792,4.080968,0.090694,"{'Fantasy': 11681, 'Young Adult': 7110, 'Roman..."
96,18966819,Pierce Brown,"Golden Son (Red Rising, #2)",2015,4361,4.374914,0.090409,"{'Science Fiction': 2613, 'Fantasy': 1372, 'Sc..."
97,3636,Lois Lowry,"The Giver (The Giver, #1)",2006,4667,4.098564,0.088832,"{'Young Adult': 10993, 'Fiction': 9045, 'Class..."
98,18293427,Gabrielle Zevin,The Storied Life of A.J. Fikry,2014,4674,4.092640,0.088795,"{'Fiction': 3795, 'Contemporary': 1100, 'Writi..."
99,26252859,Rick Riordan,"The Hidden Oracle (The Trials of Apollo, #1)",2016,4371,4.293068,0.088419,"{'Fantasy': 3173, 'Fantasy-Mythology': 1514}"

In [11]:
cold_users_events_with_recs = \
    events_test[events_test["user_id"].isin(cold_users)] \
    .merge(top_k_pop_items, on="item_id", how="left")

cold_user_items_no_avg_rating_idx = cold_users_events_with_recs["avg_rating"].isnull()
cold_user_recs = cold_users_events_with_recs[~cold_user_items_no_avg_rating_idx] \
    [["user_id", "item_id", "rating", "avg_rating"]]

In [12]:

# посчитаем метрики рекомендаций
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [13]:


rmse = mean_squared_error(cold_user_recs["rating"], cold_user_recs["avg_rating"], squared=False)
mae = mean_absolute_error(cold_user_recs["rating"], cold_user_recs["avg_rating"])
print(round(rmse, 2), round(mae, 2))

0.78 0.62

In [14]:
# посчитаем покрытие холодных пользователей рекомендациями

cold_users_hit_ratio = cold_users_events_with_recs.groupby("user_id").agg(hits=("avg_rating", lambda x: (~x.isnull()).mean()))

print(f"Доля пользователей без релевантных рекомендаций: {(cold_users_hit_ratio == 0).mean().iat[0]:.2f}")
print(f"Среднее покрытие пользователей: {cold_users_hit_ratio[cold_users_hit_ratio != 0].mean().iat[0]:.2f}")

Доля пользователей без релевантных рекомендаций: 0.59
Среднее покрытие пользователей: 0.44

In [15]:
users_id = events[['user_id']]
item_id = events[['item_id']]
user_x_item = users_id.join(item_id, how ='left')
user_x_item_x_rating = user_x_item.merge(events[['user_id', 'item_id', 'rating']], how = 'left', left_on = ['user_id', 'item_id'], right_on = ['user_id', 'item_id'])

In [16]:
user_x_item_x_rating['rating'].isna().value_counts()

rating
False    11751086
Name: count, dtype: int64

In [17]:

print(events['user_id'].nunique())

print(events['item_id'].nunique())

print(events['item_id'].nunique()*events['user_id'].nunique())

print(events['item_id'].count()/(events['item_id'].nunique()*events['user_id'].nunique()))

430585
41673
17943768705
0.0006548839428991069

In [18]:
from surprise import Dataset, Reader
from surprise import SVD

# используем Reader из библиотеки surprise для преобразования событий (events)
# в формат, необходимый surprise
reader = Reader(rating_scale=(1, 5))
surprise_train_set = Dataset.load_from_df(events_train[['user_id', 'item_id', 'rating']], reader)
surprise_train_set = surprise_train_set.build_full_trainset()

# инициализируем модель
svd_model = SVD(n_factors=100, random_state=0)

# обучаем модель
svd_model.fit(surprise_train_set)

In [19]:
surprise_test_set = list(events_test[['user_id', 'item_id', 'rating']].itertuples(index=False))

# получаем рекомендации для тестовой выборки
svd_predictions = svd_model.test(surprise_test_set)

In [20]:
from surprise import accuracy

rmse_svd = accuracy.rmse(svd_predictions)
mae_svd = accuracy.mae(svd_predictions)
                     
print(rmse, mae)

RMSE: 0.8289
MAE:  0.6474
0.7762619978173375 0.6245197878742732

In [21]:
from surprise import NormalPredictor

# инициализируем состояние генератора, это необходимо для получения
# одной и той же последовательности случайных чисел, только в учебных целях
np.random.seed(0)

random_model = NormalPredictor()

random_model.fit(surprise_train_set)
random_predictions = random_model.test(surprise_test_set)

In [22]:
rmse_random = accuracy.rmse(random_predictions)
mae_random = accuracy.mae(random_predictions)
                     
print(rmse, mae)

RMSE: 1.2628
MAE:  1.0018
0.7762619978173375 0.6245197878742732

In [23]:
mae_random/mae_svd

1.5472886771309964

In [24]:
def get_recommendations_svd(user_id, all_items, events, model, include_seen=True, n=5):

    """ возвращает n рекомендаций для user_id """
    
    # получим список идентификаторов всех книг
    all_items = set(events['item_id'].unique())
        
    # учитываем флаг, стоит ли уже прочитанные книги включать в рекомендации
    if include_seen:
        items_to_predict = list(all_items)
    else:
        # получим список книг, которые пользователь уже прочитал ("видел")
        seen_items = set(events[events['is_read']==True]['item_id'].unique())
        
        # книги, которые пользователь ещё не читал
        # только их и будем включать в рекомендации
        items_to_predict = list(all_items - seen_items)
    
    # получаем скоры для списка книг, т. е. рекомендации
    predictions = [model.predict(user_id, item_id) for item_id in items_to_predict]
    
    # сортируем рекомендации по убыванию скора и берём только n первых
    recommendations = sorted(predictions, key=lambda x: x.est, reverse=True)[:n]
    
    return pd.DataFrame([(pred.iid, pred.est) for pred in recommendations], columns=["item_id", "score"])

In [25]:
df_rec = get_recommendations_svd(1296647, items, events_test, svd_model)

In [26]:
df_rec.sort_values(by = 'score', ascending = False)

    item_id     score
0   7864312  4.981188
1  25793186  4.912001
2  12174312  4.898052
3     13208  4.894869
4  33353628  4.891661

In [27]:
# выберем произвольного пользователя из тренировочной выборки ("прошлого")
user_id = events_train['user_id'].sample().iat[0]

print(f"user_id: {user_id}")

print("История (последние события, recent)")
user_history = (
    events_train
    .query("user_id == @user_id")
    .merge(items.set_index("item_id")[["author", "title", "genre_and_votes"]], on="item_id")
)
user_history_to_print = user_history[["author", "title", "started_at", "read_at", "rating", "genre_and_votes"]].tail(10)
display(user_history_to_print)

print("Рекомендации")
user_recommendations = get_recommendations_svd(user_id, items, events_train, svd_model)
user_recommendations = user_recommendations.merge(items[["item_id", "author", "title", "genre_and_votes"]], on="item_id")

user_id: 1169023
История (последние события, recent)

,author,title,started_at,read_at,rating,genre_and_votes
68,Veronica Roth,"Divergent (Divergent, #1)",2014-06-02,2014-06-04,4,"{'Young Adult': 20260, 'Science Fiction-Dystop..."
69,"Gillian Flynn, В. Русанов",Gone Girl,2014-05-27,2014-05-29,5,"{'Fiction': 11773, 'Mystery': 9965, 'Thriller'..."
70,Kathy Reichs,"Death du Jour (Temperance Brennan, #2)",2014-05-24,2014-05-27,4,"{'Mystery': 1206, 'Mystery-Crime': 579, 'Ficti..."
71,Chelsea Cain,"Heartsick (Archie Sheridan & Gretchen Lowell, #1)",2014-05-22,2014-05-22,5,"{'Mystery': 832, 'Thriller': 653, 'Fiction': 4..."
72,"Jussi Adler-Olsen, Lisa Hartford","The Keeper of Lost Causes (Department Q, #1)",2014-05-30,2014-06-02,3,"{'Mystery': 1225, 'Mystery-Crime': 627, 'Ficti..."
73,Gillian Flynn,Dark Places,2014-05-17,2014-05-22,4,"{'Mystery': 4534, 'Fiction': 4055, 'Thriller':..."
74,Audrey Niffenegger,Her Fearful Symmetry,2014-05-05,2014-05-08,2,"{'Fiction': 1984, 'Fantasy': 674, 'Fantasy-Par..."
75,Kathy Reichs,"Déjà Dead (Temperance Brennan, #1)",2014-05-13,2014-05-17,4,"{'Mystery': 2141, 'Fiction': 904, 'Mystery-Cri..."
76,Carolyn Parkhurst,The Dogs of Babel,2014-05-09,2014-05-10,5,"{'Fiction': 522, 'Mystery': 102, 'Animals': 77..."
77,George R.R. Martin,"A Dance with Dragons (A Song of Ice and Fire, #5)",2014-05-04,2014-05-04,5,"{'Fantasy': 22247, 'Fiction': 4512, 'Fantasy-E..."

Рекомендации

# === Базовые подходы: коллаборативная фильтрация

In [6]:
import scipy
import sklearn.preprocessing

# перекодируем идентификаторы пользователей: 
# из имеющихся в последовательность 0, 1, 2, ...
user_encoder = sklearn.preprocessing.LabelEncoder()
user_encoder.fit(events["user_id"])
events_train["user_id_enc"] = user_encoder.transform(events_train["user_id"])
events_test["user_id_enc"] = user_encoder.transform(events_test["user_id"])

# перекодируем идентификаторы объектов: 
# из имеющихся в последовательность 0, 1, 2, ...
item_encoder = sklearn.preprocessing.LabelEncoder()
item_encoder.fit(items["item_id"])
items["item_id_enc"] = item_encoder.transform(items["item_id"])
events_train["item_id_enc"] = item_encoder.transform(events_train["item_id"])
events_test["item_id_enc"] = item_encoder.transform(events_test["item_id"])

/tmp/ipykernel_130661/1044897688.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_train["user_id_enc"] = user_encoder.transform(events_train["user_id"])
/tmp/ipykernel_130661/1044897688.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_test["user_id_enc"] = user_encoder.transform(events_test["user_id"])
/tmp/ipykernel_130661/1044897688.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_train["item_id_enc"] = item_encoder.transform(events_train["item_id"])
/tmp/ipykernel_130661/1044897688.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_test["item_id_enc"] = item_encoder.transform(events_test["item_id"])

In [29]:
events_train['item_id_enc'].max()

43304

In [30]:
print(events_train['user_id_enc'].nunique())
print(events_train['item_id_enc'].nunique())

428220
41474

In [31]:
# объем таблицы
(428220*41474)/(1024**3)

16.54028546065092

In [32]:
# создаём sparse-матрицу формата CSR 
user_item_matrix_train = scipy.sparse.csr_matrix((
    events_train["rating"],
    (events_train['user_id_enc'], events_train['item_id_enc'])),
    dtype=np.int8)

In [33]:
import sys

sum([sys.getsizeof(i) for i in user_item_matrix_train.data])/1024**3

0.26370687410235405

In [34]:
from implicit.als import AlternatingLeastSquares

als_model = AlternatingLeastSquares(factors=50, iterations=50, regularization=0.05, random_state=0)
als_model.fit(user_item_matrix_train)

/home/mle-user/mle_projects/mle-recsys-start/env_recsys_start/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/mle-user/mle_projects/mle-recsys-start/env_recsys_start/lib/python3.10/site-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 4 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()
100%|██████████| 50/50 [03:41<00:00,  4.42s/it]

In [35]:
def get_recommendations_als(user_item_matrix, model, user_id, user_encoder, item_encoder, include_seen=True, n=5):
    """
    Возвращает отранжированные рекомендации для заданного пользователя
    """
    user_id_enc = user_encoder.transform([user_id])[0]
    recommendations = model.recommend(
         user_id_enc, 
         user_item_matrix[user_id_enc], 
         filter_already_liked_items=not include_seen,
         N=n)
    recommendations = pd.DataFrame({"item_id_enc": recommendations[0], "score": recommendations[1]})
    recommendations["item_id"] = item_encoder.inverse_transform(recommendations["item_id_enc"])
    
    return recommendations

In [73]:
# получаем список всех возможных user_id (перекодированных)
user_ids_encoded = range(len(user_encoder.classes_))

# получаем рекомендации для всех пользователей
als_recommendations = als_model.recommend(
    user_ids_encoded, 
    user_item_matrix_train[user_ids_encoded], 
    filter_already_liked_items=False, N=100)

In [74]:
# преобразуем полученные рекомендации в табличный формат
item_ids_enc = als_recommendations[0]
als_scores = als_recommendations[1]

als_recommendations = pd.DataFrame({
    "user_id_enc": user_ids_encoded,
    "item_id_enc": item_ids_enc.tolist(), 
    "score": als_scores.tolist()})
als_recommendations = als_recommendations.explode(["item_id_enc", "score"], ignore_index=True)

# приводим типы данных
als_recommendations["item_id_enc"] = als_recommendations["item_id_enc"].astype("int")
als_recommendations["score"] = als_recommendations["score"].astype("float")

# получаем изначальные идентификаторы
als_recommendations["user_id"] = user_encoder.inverse_transform(als_recommendations["user_id_enc"])
als_recommendations["item_id"] = item_encoder.inverse_transform(als_recommendations["item_id_enc"])
als_recommendations = als_recommendations.drop(columns=["user_id_enc", "item_id_enc"])

In [75]:
als_recommendations = als_recommendations[["user_id", "item_id", "score"]]
als_recommendations.to_parquet("als_recommendations.parquet")

In [76]:
als_recommendations = (
    als_recommendations
    .merge(events_test[["user_id", "item_id", "rating"]]
               .rename(columns={"rating": "rating_test"}), 
           on=["user_id", "item_id"], how="left")
)

In [77]:
als_recommendations.to_parquet("als_recommendations.parquet")

In [40]:
import sklearn.metrics

def compute_ndcg(rating: pd.Series, score: pd.Series, k):

    """ подсчёт ndcg
    rating: истинные оценки
    score: оценки модели
    k: количество айтемов (по убыванию score) для оценки, остальные - отбрасываются
    """
    
    # если кол-во объектов меньше 2, то NDCG - не определена
    if len(rating) < 2:
        return np.nan

    ndcg = sklearn.metrics.ndcg_score(np.asarray([rating.to_numpy()]), np.asarray([score.to_numpy()]), k=k)

    return ndcg

In [41]:
rating_test_idx = ~als_recommendations["rating_test"].isnull()
ndcg_at_5_scores = als_recommendations[rating_test_idx].groupby("user_id").apply(lambda x: compute_ndcg(x["rating_test"], x["score"], k=5))

In [42]:
print(ndcg_at_5_scores.mean())

0.975946709792109

# === Базовые подходы: контентные рекомендации

In [7]:
items["genre_and_votes"] = items["genre_and_votes"].apply(eval)

In [8]:
def get_genres(items):

    """ 
    извлекает список жанров по всем книгам, 
    подсчитывает долю голосов по каждому их них
    """
    
    genres_counter = {}
    
    for k, v, in items.iterrows():
        genre_and_votes = v.get('genre_and_votes')
        if genre_and_votes is None or not isinstance(genre_and_votes, dict):
            continue
        for genre, votes in genre_and_votes.items():
            # увеличиваем счётчик жанров
            try:
                genres_counter[genre] += votes
            except KeyError:
                genres_counter[genre] = 0

    genres = pd.Series(genres_counter, name="votes")
    genres = genres.to_frame()
    genres = genres.reset_index().rename(columns={"index": "name"})
    genres.index.name = "genre_id"
    
    return genres
   
genres = get_genres(items)

In [9]:
genres["score"] = genres["votes"] / genres["votes"].sum()
genres.sort_values(by="score", ascending=False).head(10)

                                   name    votes     score
genre_id
25                              Fantasy  6850060  0.149651
1                               Fiction  6406256  0.139955
38                             Classics  3414934  0.074605
18                          Young Adult  3296951  0.072027
34                              Romance  2422614  0.052926
5                            Nonfiction  1737406  0.037957
16        Historical-Historical Fiction  1531205  0.033452
20                              Mystery  1371196  0.029956
24                      Science Fiction  1218917  0.026629
33                   Fantasy-Paranormal   857012  0.018723

In [10]:
def get_item2genre_matrix(genres, items):

    genre_names_to_id = genres.reset_index().set_index("name")["genre_id"].to_dict()
    
    # list to build CSR matrix
    genres_csr_data = []
    genres_csr_row_idx = []
    genres_csr_col_idx = []
    
    for item_idx, (k, v) in enumerate(items.iterrows()):
        if v["genre_and_votes"] is None:
            continue
        for genre_name, votes in v["genre_and_votes"].items():
            genre_idx = genre_names_to_id[genre_name]
            genres_csr_data.append(int(votes))
            genres_csr_row_idx.append(item_idx)
            genres_csr_col_idx.append(genre_idx)

    genres_csr = scipy.sparse.csr_matrix((genres_csr_data, (genres_csr_row_idx, genres_csr_col_idx)), shape=(len(items), len(genres)))
    # нормализуем, чтобы сумма оценок принадлежности к жанру была равна 1
    genres_csr = sklearn.preprocessing.normalize(genres_csr, norm='l1', axis=1)
    
    return genres_csr

In [11]:
items = items.sort_values(by="item_id_enc")
all_items_genres_csr = get_item2genre_matrix(genres, items)

In [48]:
all_items_genres_csr

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 210895 stored elements and shape (43312, 815)>

In [49]:
user_id = 1000010
user_events = events_train.query("user_id == @user_id")[["item_id", "rating"]]
user_items = items[items["item_id"].isin(user_events["item_id"])]

In [50]:

user_items_genres_csr = get_item2genre_matrix(genres, user_items)
user_items_genres_csr

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 149 stored elements and shape (22, 815)>

In [51]:
# вычислим склонность пользователя к жанрам как среднее взвешенное значение популяции на его оценки книг.

# преобразуем пользовательские оценки из списка в вектор-столбец
user_ratings = user_events["rating"].to_numpy() / 5
user_ratings = np.expand_dims(user_ratings, axis=1)

user_items_genres_weighted = user_items_genres_csr.multiply(user_ratings)

user_genres_scores = np.asarray(user_items_genres_weighted.mean(axis=0))

In [52]:
# выведем список жанров, которые предпочитает пользователь

user_genres = genres.copy()
user_genres["score"] = np.ravel(user_genres_scores)
user_genres = user_genres[user_genres["score"] > 0].sort_values(by=["score"], ascending=False)

user_genres.head(5)

                     name    votes     score
genre_id
1                 Fiction  6406256  0.185241
38               Classics  3414934  0.103879
25                Fantasy  6850060  0.072447
5              Nonfiction  1737406  0.050865
24        Science Fiction  1218917  0.040920

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

# вычисляем сходство между вектором пользователя и векторами по книгам
similarity_scores = cosine_similarity(all_items_genres_csr, user_genres_scores)

# преобразуем в одномерный массив
similarity_scores = similarity_scores.flatten()

# получаем индексы top-k (по убыванию значений), по сути, индексы книг (encoded)
k = 5
top_k_indices = np.argsort(similarity_scores)[-k:][::-1]

In [54]:
top_k_indices

array([ 4471, 36093, 14087,  9476,  4460])

In [55]:
similarity_scores

array([0.50714765, 0.49770536, 0.52433355, ..., 0.64894348, 0.03112624,
       0.29805756])

In [56]:
selected_items = items[items["item_id_enc"].isin(top_k_indices)]

with pd.option_context("max_colwidth", 100):
   display(selected_items[["author", "title", "genre_and_votes"]])

,author,title,genre_and_votes
80465,G.K. Chesterton,The Napoleon of Notting Hill,"{'Fiction': 166, 'Classics': 88, 'Fantasy': 44, 'Humor': 22, 'Literature': 20}"
1168335,Ray Bradbury,"Dandelion Wine (Green Town, #1)","{'Fiction': 1438, 'Classics': 914, 'Science Fiction': 529, 'Fantasy': 456, 'Young Adult': 212}"
393210,"G.K. Chesterton, Jonathan Lethem",The Man Who Was Thursday: A Nightmare,"{'Fiction': 1257, 'Classics': 929, 'Mystery': 469, 'Fantasy': 293, 'Philosophy': 156, 'Literatur..."
2244467,Samuel Butler,"Erewhon (Erewhon , #1)","{'Fiction': 162, 'Classics': 139, 'Science Fiction': 60, 'Fantasy': 55}"
39408,"Paulo Coelho, Alan R. Clarke, James Noel Smith",The Alchemist,"{'Fiction': 14023, 'Classics': 5787, 'Fantasy': 3289, 'Philosophy': 2759}"

In [57]:
top_k_indices

array([ 4471, 36093, 14087,  9476,  4460])

# === Базовые подходы: валидация

In [12]:
def process_events_recs_for_binary_metrics(events_train, events_test, recs, top_k=None):

    """
    размечает пары <user_id, item_id> для общего множества пользователей признаками
    - gt (ground truth)
    - pr (prediction)
    top_k: расчёт ведётся только для top k-рекомендаций
    """

    events_test["gt"] = True
    common_users = set(events_test["user_id"]) & set(recs["user_id"])

    print(f"Common users: {len(common_users)}")
    
    events_for_common_users = events_test[events_test["user_id"].isin(common_users)].copy()
    recs_for_common_users = recs[recs["user_id"].isin(common_users)].copy()

    recs_for_common_users = recs_for_common_users.sort_values(["user_id", "score"], ascending=[True, False])

    # оставляет только те item_id, которые были в events_train, 
    # т. к. модель не имела никакой возможности давать рекомендации для новых айтемов
    events_for_common_users = events_for_common_users[events_for_common_users["item_id"].isin(events_train["item_id"].unique())]

    if top_k is not None:
        recs_for_common_users = recs_for_common_users.groupby("user_id").head(top_k)
    
    events_recs_common = events_for_common_users[["user_id", "item_id", "gt"]].merge(
        recs_for_common_users[["user_id", "item_id", "score"]], 
        on=["user_id", "item_id"], how="outer")    

    events_recs_common["gt"] = events_recs_common["gt"].fillna(False)
    events_recs_common["pr"] = ~events_recs_common["score"].isnull()
    
    events_recs_common["tp"] = events_recs_common["gt"] & events_recs_common["pr"]
    events_recs_common["fp"] = ~events_recs_common["gt"] & events_recs_common["pr"]
    events_recs_common["fn"] = events_recs_common["gt"] & ~events_recs_common["pr"]

    return events_recs_common

In [59]:
events_recs_for_binary_metrics = process_events_recs_for_binary_metrics(
  events_train,
    events_test, 
    als_recommendations, 
    top_k=5)

/tmp/ipykernel_5347/3166051426.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_test["gt"] = True

Common users: 123223

In [60]:
events_recs_for_binary_metrics.head(2)

   user_id   item_id    gt  score     pr     tp     fp    fn
0  1196635  18467802  True    NaN  False  False  False  True
1  1188739     10799  True    NaN  False  False  False  True

In [13]:
def compute_cls_metrics(events_recs_for_binary_metric):
    
    groupper = events_recs_for_binary_metric.groupby("user_id")

    # precision = tp / (tp + fp)
    precision = groupper["tp"].sum()/(groupper["tp"].sum()+groupper["fp"].sum())
    precision = precision.mean()
    
    # recall = tp / (tp + fn)
    recall =  groupper["tp"].sum()/(groupper["tp"].sum()+groupper["fn"].sum())
    recall = recall.mean()

    return precision, recall

In [62]:
precision, recall = compute_cls_metrics(events_recs_for_binary_metrics)

In [63]:
print(precision, recall)

0.007581376853347184 0.014248299488677446

# === Двухстадийный подход: метрики

In [14]:
als_recommendations = pd.read_parquet("als_recommendations.parquet")

In [7]:
# расчёт покрытия по объектам
cov_items = als_recommendations['item_id'].nunique()/items['item_id'].nunique()
print(f"{cov_items:.2f}")

0.09

In [8]:
als_recommendations['rating_test'].value_counts()

rating_test
5.0    34710
4.0    29713
3.0    12687
2.0     2743
1.0      641
Name: count, dtype: int64

In [9]:
als_recommendations.query('~rating_test.isna()')

          user_id   item_id     score  rating_test
611       1000006  18774964  0.367940          4.0
615       1000006  29868610  0.289370          4.0
633       1000006      7445  0.229146          4.0
664       1000006  18812405  0.162832          3.0
687       1000006  24817626  0.136432          3.0
...           ...       ...       ...          ...
43056981  1430569  28763485  0.225379          5.0
43057389  1430573      1618  0.100608          4.0
43057861  1430578     17061  0.613498          5.0
43057873  1430578    830502  0.570653          5.0
43058430  1430584  18692431  0.182658          3.0

[80494 rows x 4 columns]

In [10]:
# разметим каждую рекомендацию признаком read
events_train["read"] = True
als_recommendations = als_recommendations.merge(events_train, on=["user_id", "item_id"], how="left")
als_recommendations["read"] = als_recommendations["read"].fillna(False).astype("bool")

/tmp/ipykernel_6052/3104705113.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_train["read"] = True

In [20]:
als_recommendations[als_recommendations['user_id'] == 1000000]

,user_id,item_id,score,rating_test,started_at,read_at,is_read,rating,is_reviewed,started_at_month,user_id_enc,item_id_enc,read,rank
0,1000000,3,0.990941,NaN,2011-11-04,2011-11-20,True,5.0,False,2011-11-01,0.0,2.0,True,1
1,1000000,15881,0.896617,NaN,2008-08-03,2008-08-26,True,5.0,False,2008-08-01,0.0,1942.0,True,2
2,1000000,5,0.864404,NaN,2012-10-02,2012-10-24,True,5.0,False,2012-10-01,0.0,3.0,True,3
3,1000000,6,0.822254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,4
4,1000000,2,0.774095,NaN,2009-07-12,2009-07-29,True,5.0,False,2009-07-01,0.0,1.0,True,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1000000,4588,0.229302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,96
96,1000000,128029,0.226873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,97
97,1000000,10626594,0.226123,NaN,2016-06-02,2016-06-09,True,5.0,False,2016-06-01,0.0,28836.0,True,98
98,1000000,12812550,0.225484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,99
99,1000000,231804,0.225466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,100

In [15]:
# оставляем только тех пользователей, что есть в тестовой выборке, для экономии ресурсов
candidates_to_rank = candidates_to_rank[candidates_to_rank["user_id"].isin(events_test_2["user_id"].drop_duplicates())]
print(len(candidates_to_rank))

NameError: name 'candidates_to_rank' is not defined

# === Двухстадийный подход: модель

In [16]:
# задаём точку разбиения
split_date_for_labels = pd.to_datetime("2017-09-15").date()

split_date_for_labels_idx = events_test["started_at"] < split_date_for_labels
events_labels = events_test[split_date_for_labels_idx].copy()
events_test_2 = events_test[~split_date_for_labels_idx].copy()

In [7]:
events_labels['user_id'].nunique()

99849

In [17]:
# загружаем рекомендации от двух базовых генераторов
als_recommendations = pd.read_parquet("candidates/training/als_recommendations.parquet")
content_recommendations = pd.read_parquet("candidates/training/content_recommendations.parquet")

candidates = pd.merge(
    als_recommendations[["user_id", "item_id", "score"]].rename(columns={"score": "als_score"}),
    content_recommendations[["user_id", "item_id", "score"]].rename(columns={"score": "cnt_score"}),
    on=["user_id", "item_id"],
    how="outer")

In [18]:
# добавляем таргет к кандидатам со значением:
# — 1 для тех item_id, которые пользователь прочитал
# — 0, для всех остальных 

events_labels["target"] = 1
candidates = candidates.merge(events_labels[["user_id", "item_id", "target"]], 
                             on=["user_id", "item_id"],
                             how = 'left')
candidates["target"] = candidates["target"].fillna(0).astype("int")

# в кандидатах оставляем только тех пользователей, у которых есть хотя бы один положительный таргет
candidates_to_sample = candidates.groupby("user_id").filter(lambda x: x["target"].sum() > 0)

In [19]:

# для каждого пользователя оставляем только 4 негативных примера
negatives_per_user = 4
candidates_for_train = pd.concat([
    candidates_to_sample.query('target == 1'),
    candidates_to_sample.query("target == 0") \
        .groupby("user_id") \
        .apply(lambda x: x.sample(negatives_per_user, random_state=0))
    ])

In [20]:
from catboost import CatBoostClassifier, Pool

# задаём имена колонок признаков и таргета
features = ['als_score', 'cnt_score']
target = 'target'

# Create the Pool object
train_data = Pool(
    data=candidates_for_train[features], 
    label=candidates_for_train[target])

# инициализируем модель CatBoostClassifier
cb_model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.1,
    depth=6,
    loss_function='Logloss',
    verbose=100,
    random_seed=0
)

# тренируем модель
cb_model.fit(train_data)

0:	learn: 0.6526057	total: 72.1ms	remaining: 1m 12s
100:	learn: 0.5118959	total: 2.96s	remaining: 26.4s
200:	learn: 0.5111710	total: 5.53s	remaining: 22s
300:	learn: 0.5105208	total: 9.33s	remaining: 21.7s
400:	learn: 0.5100174	total: 12.6s	remaining: 18.9s
500:	learn: 0.5095747	total: 15s	remaining: 14.9s
600:	learn: 0.5091600	total: 17.5s	remaining: 11.6s
700:	learn: 0.5087803	total: 19.7s	remaining: 8.38s
800:	learn: 0.5084220	total: 22.7s	remaining: 5.63s
900:	learn: 0.5080930	total: 25.1s	remaining: 2.75s
999:	learn: 0.5078081	total: 27.7s	remaining: 0us

In [21]:
# загружаем рекомендации от двух базовых генераторов
als_recommendations_2 = pd.read_parquet("candidates/inference/als_recommendations.parquet")
content_recommendations_2 = pd.read_parquet("candidates/inference/content_recommendations.parquet")

candidates_to_rank = pd.merge(als_recommendations_2[["user_id", "item_id", "score"]].rename(columns={"score": "als_score"}),
    content_recommendations_2[["user_id", "item_id", "score"]].rename(columns={"score": "cnt_score"}), on = ['user_id', 'item_id'], how='outer')

# оставляем только тех пользователей, что есть в тестовой выборке, для экономии ресурсов
candidates_to_rank = candidates_to_rank[candidates_to_rank["user_id"].isin(events_test_2["user_id"].drop_duplicates())]
print(len(candidates_to_rank))

14517152

In [22]:
inference_data = Pool(data=candidates_to_rank[features])
predictions = cb_model.predict_proba(inference_data)

candidates_to_rank["cb_score"] = predictions[:, 1]

# для каждого пользователя проставляем rank, начиная с 1 — это максимальный cb_score
candidates_to_rank = candidates_to_rank.sort_values(["user_id", "cb_score"], ascending=[True, False])
candidates_to_rank["rank"] = candidates_to_rank.groupby("user_id").cumcount() + 1

max_recommendations_per_user = 100
final_recommendations = candidates_to_rank[candidates_to_rank['rank'] <= max_recommendations_per_user]

In [14]:
final_recommendations

          user_id   item_id  als_score  cnt_score  cb_score  rank
347       1000003     49628   0.446143   0.906649  0.583617     1
300       1000003   7260188   1.129979        NaN  0.509005     2
301       1000003   6148028   1.123475        NaN  0.509005     3
302       1000003   2767052   1.112699        NaN  0.509005     4
320       1000003     43641   0.617602        NaN  0.477032     5
...           ...       ...        ...        ...       ...   ...
43058095  1430580  23705512   0.016477        NaN  0.232760    96
43058096  1430580   6314763   0.016404        NaN  0.232760    97
43058097  1430580  11710373   0.016035        NaN  0.221228    98
43058098  1430580      7445   0.015793        NaN  0.221228    99
43058099  1430580  17802724   0.015771        NaN  0.221228   100

[7519400 rows x 6 columns]

In [23]:
events_inference = pd.concat([events_train, events_labels])

cb_events_recs_for_binary_metrics_5 = process_events_recs_for_binary_metrics(
    events_inference,
    events_test_2,
    final_recommendations.rename(columns={"cb_score": "score"}), 
    top_k=5)

cb_precision_5, cb_recall_5 = compute_cls_metrics(cb_events_recs_for_binary_metrics_5)

print(f"precision: {cb_precision_5:.3f}, recall: {cb_recall_5:.3f}")

Common users: 75194
precision: 0.006, recall: 0.015

# === Двухстадийный подход: построение признаков

In [19]:
candidates_for_train

                     user_id   item_id  als_score  cnt_score  target
615                  1000006  29868610   0.286715        NaN       1
632                  1000006      7445   0.230529        NaN       1
649                  1000006  18812405   0.178382        NaN       1
1998                 1000019     37415   0.043595        NaN       1
2302                 1000023   7260188   0.598791        NaN       1
...                      ...       ...        ...        ...     ...
(1430579, 82992597)  1430579  15698462        NaN   0.900922       0
(1430584, 43058418)  1430584  18774964   0.222126        NaN       0
(1430584, 82993064)  1430584   8393104        NaN   0.795215       0
(1430584, 82993001)  1430584     24929        NaN   0.847833       0
(1430584, 43058493)  1430584      5129   0.094607        NaN       0

[213708 rows x 5 columns]

In [21]:
candidates_to_rank

          user_id  item_id  als_score  cnt_score  cb_score  rank
347       1000003    49628   0.446143   0.906649  0.583617     1
300       1000003  7260188   1.129979        NaN  0.509005     2
301       1000003  6148028   1.123475        NaN  0.509005     3
302       1000003  2767052   1.112699        NaN  0.509005     4
320       1000003    43641   0.617602        NaN  0.477032     5
...           ...      ...        ...        ...       ...   ...
82993814  1430580   183087        NaN   0.981247  0.066960   187
82993807  1430580    33906        NaN   0.988908  0.064737   188
82993808  1430580    82436        NaN   0.987934  0.064737   189
82993809  1430580    82780        NaN   0.987217  0.061955   190
82993810  1430580    82783        NaN   0.985955  0.056530   191

[14517152 rows x 6 columns]

In [20]:
items

,item_id,author,title,description,genre_and_votes,num_pages,average_rating,ratings_count,text_reviews_count,publisher,publication_year,country_code,language_code,format,is_ebook,isbn,isbn13,genre_and_votes_dict,genre_and_votes_str
3,6066819,Jennifer Weiner,Best Friends Forever,Addie Downs and Valerie Adler were eight when ...,"{'Womens Fiction-Chick Lit': 739, 'Fiction': 442}",368,3.49,51184,3282,Atria Books,2009,US,eng,Hardcover,False,0743294297,9780743294294,"{'Academic': None, 'Academic-Academia': None, ...","Womens Fiction-Chick Lit 739, Fiction 442"
6,378460,Michael Halberstam,The Wanting of Levine,,"{'Politics': 1, 'Humor': 1}",<NA>,4.38,12,4,Berkley Publishing Group,1979,US,,Paperback,False,0425040887,9780425040881,"{'Academic': None, 'Academic-Academia': None, ...","Politics 1user, Humor 1user"
15,89375,"Don Piper, Cecil Murphey",90 Minutes in Heaven: A True Story of Death an...,As he is driving home from a minister's confer...,"{'Christian': 395, 'Nonfiction': 392, 'Religio...",<NA>,3.91,68157,2885,,<NA>,US,,,False,0800759494,9780800759490,"{'Academic': None, 'Academic-Academia': None, ...","Christian 395, Nonfiction 392, Religion 142, S..."
16,89376,Randy Alcorn,Heaven,What is Heaven really going to be like? What w...,"{'Christian': 225, 'Religion-Theology': 154, '...",533,4.26,7345,566,,<NA>,US,eng,,False,0842379428,9780842379427,"{'Academic': None, 'Academic-Academia': None, ...","Christian 225, Religion-Theology 154, Nonficti..."
17,89377,Jennifer L. Holm,Penny from Heaven,It's 1953 and 11-year-old Penny dreams of a su...,"{'Historical-Historical Fiction': 284, 'Childr...",288,3.98,6949,615,Random House Books for Young Readers,2006,US,,Hardcover,False,037583687X,9780375836879,"{'Academic': None, 'Academic-Academia': None, ...","Historical-Historical Fiction 284, Childrens-M..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2360257,279660,James Goldman,The Lion in Winter,Insecure siblings fighting for their parents' ...,"{'Plays': 294, 'Historical-Historical Fiction'...",103,4.22,8227,100,Random House,2004,US,eng,Paperback,False,0812973356,9780812973358,"{'Academic': None, 'Academic-Academia': None, ...","Plays 294, Historical-Historical Fiction 110, ..."
2360258,7657484,"J. Michael Straczynski, Shane Davis, Sandra Ho...","Superman: Earth One, Volume 1",Forget everything you know about The Man of St...,"{'Sequential Art-Comics': 683, 'Sequential Art...",134,3.90,13221,578,DC Comics,2010,US,eng,Hardcover,False,1401224687,9781401224684,"{'Academic': None, 'Academic-Academia': None, ...","Sequential Art-Comics 683, Sequential Art-Grap..."
2360322,7715664,Larissa Ione,Sin Undone (Demonica #5),HER TOUCH IS DEADLY\nAs the only female Seminu...,"{'Romance-Paranormal Romance': 703, 'Fantasy-P...",400,4.35,23091,819,Grand Central Publishing,2010,US,eng,Mass Market Paperback,False,0446556815,9780446556811,"{'Academic': None, 'Academic-Academia': None, ...","Romance-Paranormal Romance 703, Fantasy-Parano..."
2360395,30367813,J.A. Owenby,The Truth She Knew (The Truth Series #1),"""A bittersweet story of young love, independen...","{'Fiction': 4, 'Romance': 3, 'Business-Amazon'...",238,4.34,111,67,,2016,US,eng,Paperback,False,1533660549,9781533660541,"{'Academic': None, 'Academic-Academia': None, ...","Fiction 4, Romance 3, Business-Amazon 3"
2360448,282240,Geoffrey Huntington,"Demon Witch (The Ravenscliff, #2)",Devon March matches wits and wizardry against ...,"{'Fantasy': 33, 'Young Adult': 16, 'Horror': 1...",388,3.99,491,17,ReganBooks,2004,US,,Paperback,False,0060595515,9780060595517,"{'Academic': None, 'Academic-Academia': None, ...","Fantasy 33, Young Adult 16, Horror 13, Fantasy..."

In [24]:
items["age"] = 2018 - items["publication_year"]
invalid_age_idx = items["age"] < 0
items.loc[invalid_age_idx, "age"] = np.nan
items["age"] = items["age"].astype("float")

candidates_for_train = candidates_for_train.merge(items[['item_id', 'age']], on = 'item_id', how = 'left')
candidates_to_rank = candidates_to_rank.merge(items[['item_id', 'age']] , on = 'item_id', how = 'left')

In [26]:
candidates_to_rank['age'].median()

7.0

In [27]:
events

,user_id,item_id,started_at,read_at,is_read,rating,is_reviewed,started_at_month
0,1229132,22034,2015-07-12,2015-07-17,True,5,False,2015-07-01
1,1229132,22318578,2015-06-07,2015-08-09,True,5,True,2015-06-01
2,1229132,22551730,2015-06-24,2015-07-11,True,4,True,2015-06-01
3,1229132,22816087,2015-09-27,2015-11-04,True,5,True,2015-09-01
5,1229132,17910054,2015-03-04,2015-07-28,True,3,False,2015-03-01
...,...,...,...,...,...,...,...,...
12914452,1364473,5297,2017-02-07,2017-02-26,True,5,False,2017-02-01
12914453,1364473,4900,2016-12-22,2016-12-29,True,2,False,2016-12-01
12914454,1364473,14836,2016-11-29,2017-01-15,True,3,False,2016-11-01
12914456,1297020,10210,2012-06-05,2013-01-17,True,5,False,2012-06-01
12914457,1297020,99561,2012-07-21,2012-07-22,True,4,False,2012-07-01

In [25]:
def get_user_features(events):
    """ считает пользовательские признаки """
    
    user_features = events.groupby("user_id").agg(
        reading_years=("started_at", lambda x: (x.max()-x.min()).days/365.25),
        books_read=("item_id", "count"),
        rating_avg=("rating", "mean"),
        rating_std=("rating", "std"))
    
    user_features["books_per_year"] = user_features["books_read"] / user_features["reading_years"]
    
    return user_features
    
user_features_for_train = get_user_features(events_train)
candidates_for_train = candidates_for_train.merge(user_features_for_train, on="user_id", how="left")
  
# оставим только тех пользователей, что есть в тесте, для экономии ресурсов
events_inference = pd.concat([events_train, events_labels])
events_inference = events_inference[events_inference["user_id"].isin(events_test["user_id"].drop_duplicates())]

user_features_for_ranking = get_user_features(events_inference)
candidates_to_rank = candidates_to_rank.merge(user_features_for_ranking, on="user_id", how="left")

In [29]:
candidates_for_train['books_read'].median()

32.0

In [28]:
genres.sort_values("votes", ascending=False).head(genres_top_k)

                                   name    votes     score
genre_id
25                              Fantasy  6850060  0.149651
1                               Fiction  6406256  0.139955
38                             Classics  3414934  0.074605
18                          Young Adult  3296951  0.072027
34                              Romance  2422614  0.052926
5                            Nonfiction  1737406  0.037957
16        Historical-Historical Fiction  1531205  0.033452
20                              Mystery  1371196  0.029956
24                      Science Fiction  1218917  0.026629
33                   Fantasy-Paranormal   857012  0.018723

In [26]:
# определяем индексы топ-10 жанров и всех остальных
genres_top_k = 10
genres_top_idx = genres.sort_values("votes", ascending=False).head(genres_top_k).index
genres_others_idx = list(set(genres.index) - set(genres_top_idx))

genres_top_columns = [f"genre_{id}" for id in genres_top_idx]
genres_others_column = "genre_others"
genre_columns = genres_top_columns + [genres_others_column]

# составляем таблицу принадлежности книг к жанрам
item_genres = (
    pd.concat([
        # топ жанров
        pd.DataFrame(all_items_genres_csr[:, genres_top_idx].toarray(), columns=genres_top_columns),
        # все остальные жанры
        pd.DataFrame(all_items_genres_csr[:, genres_others_idx].sum(axis=1), columns=[genres_others_column])
        ],
        axis=1)
    .reset_index()
    .rename(columns={"index": "item_id_enc"})
)

# объединяем информацию принадлежности книг к жанрам с основной информацией о книгах
items = items.merge(item_genres, on="item_id_enc", how="left")

def get_user_genres(events, items, item_genre_columns):
    user_genres = (
        events
        .merge(items[["item_id"] + item_genre_columns], on="item_id", how="left")
        .groupby("user_id")[item_genre_columns].mean()
    )
    return user_genres
    
user_genres_for_train = get_user_genres(events_train, items, genre_columns)
candidates_for_train = candidates_for_train.merge(user_genres_for_train, on="user_id", how="left")

user_genres_for_ranking = get_user_genres(events_inference, items, genre_columns)
candidates_to_rank = candidates_to_rank.merge(user_genres_for_ranking, on="user_id", how="left")

In [29]:
candidates_for_train['genre_34'].median()

0.038488976462249

In [31]:
candidates_for_train

,user_id,item_id,als_score,cnt_score,target,age,reading_years,books_read,rating_avg,rating_std,...,genre_1,genre_38,genre_18,genre_34,genre_5,genre_16,genre_20,genre_24,genre_33,genre_others
0,1000006,29868610,0.286715,NaN,1,NaN,1.820671,17.0,4.294118,0.685994,...,0.246138,0.105182,0.057684,0.010375,0.078927,0.004294,0.021665,0.008603,0.000000,0.286282
1,1000006,7445,0.230529,NaN,1,12.0,1.820671,17.0,4.294118,0.685994,...,0.246138,0.105182,0.057684,0.010375,0.078927,0.004294,0.021665,0.008603,0.000000,0.286282
2,1000006,18812405,0.178382,NaN,1,4.0,1.820671,17.0,4.294118,0.685994,...,0.246138,0.105182,0.057684,0.010375,0.078927,0.004294,0.021665,0.008603,0.000000,0.286282
3,1000019,37415,0.043595,NaN,1,12.0,0.276523,6.0,4.166667,1.169045,...,0.158224,0.000000,0.000000,0.000000,0.195082,0.000000,0.000000,0.082617,0.000000,0.514445
4,1000023,7260188,0.598791,NaN,1,8.0,0.005476,2.0,3.500000,0.707107,...,0.170366,0.000000,0.159612,0.019622,0.000000,0.000000,0.000000,0.077326,0.000000,0.254950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213703,1430579,15698462,NaN,0.900922,0,6.0,6.499658,264.0,3.928030,1.143061,...,0.069304,0.007392,0.271108,0.080489,0.017241,0.007644,0.027871,0.021434,0.020003,0.300587
213704,1430584,18774964,0.222126,NaN,0,4.0,2.899384,11.0,3.454545,1.128152,...,0.224713,0.017886,0.061621,0.047617,0.084946,0.020774,0.041339,0.002553,0.001796,0.339348
213705,1430584,8393104,NaN,0.795215,0,8.0,2.899384,11.0,3.454545,1.128152,...,0.224713,0.017886,0.061621,0.047617,0.084946,0.020774,0.041339,0.002553,0.001796,0.339348
213706,1430584,24929,NaN,0.847833,0,16.0,2.899384,11.0,3.454545,1.128152,...,0.224713,0.017886,0.061621,0.047617,0.084946,0.020774,0.041339,0.002553,0.001796,0.339348
213707,1430584,5129,0.094607,NaN,0,20.0,2.899384,11.0,3.454545,1.128152,...,0.224713,0.017886,0.061621,0.047617,0.084946,0.020774,0.041339,0.002553,0.001796,0.339348

In [40]:
candidates_for_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213708 entries, 0 to 213707
Data columns (total 22 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   user_id         213708 non-null  int64
 1   item_id         213708 non-null  int64
 2   als_score       138268 non-null  float64
 3   cnt_score       85345 non-null   float64
 4   target          213708 non-null  int64
 5   age             189704 non-null  float64
 6   reading_years   213222 non-null  float64
 7   books_read      213222 non-null  float64
 8   rating_avg      213222 non-null  float64
 9   rating_std      208974 non-null  float64
 10  books_per_year  213222 non-null  float64
 11  genre_25        213222 non-null  float64
 12  genre_1         213222 non-null  float64
 13  genre_38        213222 non-null  float64
 14  genre_18        213222 non-null  float64
 15  genre_34        213222 non-null  float64
 16  genre_5         213222 non-null  float64
 17  genre_16        213222 non-null  float64
 18  genre_20        213222 non-null  float64
 19  genre_24        213222 non-null  float64
 20  genre_33        213222 non-null  float64
 21  genre_others    213222 non-null  float64
dtypes: float64(19), int64(3)
memory usage: 35.9 MB

In [41]:
items

,item_id,author,title,description,genre_and_votes,num_pages,average_rating,ratings_count,text_reviews_count,publisher,...,genre_1,genre_38,genre_18,genre_34,genre_5,genre_16,genre_20,genre_24,genre_33,genre_others
0,1,J.K. Rowling,Harry Potter and the Half-Blood Prince (Harry ...,The war against Voldemort is not going well: e...,"{'Fantasy': 46400, 'Young Adult': 15083, 'Fict...",652,4.54,1713866,22680,Scholastic Inc.,...,0.148026,0.014064,0.170655,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.142267
1,2,"J.K. Rowling, Mary GrandPré",Harry Potter and the Order of the Phoenix (Har...,Harry Potter is due to start his fifth year at...,"{'Fantasy': 46485, 'Young Adult': 15194, 'Fict...",870,4.47,1766895,23679,Scholastic Inc.,...,0.174786,0.000000,0.203283,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000
2,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,Harry Potter's life is miserable. His parents ...,"{'Fantasy': 59818, 'Fiction': 17918, 'Young Ad...",320,4.45,4765497,59856,Scholastic Inc,...,0.154140,0.022797,0.153916,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.154561
3,5,"J.K. Rowling, Mary GrandPré",Harry Potter and the Prisoner of Azkaban (Harr...,Harry Potter's third year at Hogwarts is full ...,"{'Fantasy': 49784, 'Young Adult': 15393, 'Fict...",435,4.53,1876252,28561,Scholastic Inc.,...,0.148702,0.015347,0.160382,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.156860
4,6,"J.K. Rowling, Mary GrandPré",Harry Potter and the Goblet of Fire (Harry Pot...,Harry Potter is midway through his training as...,"{'Fantasy': 48257, 'Young Adult': 15483, 'Fict...",734,4.53,1792561,25258,Scholastic Inc.,...,0.176369,0.000000,0.200067,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43307,36411879,Lylah James,The Mafia And His Angel: Part 2 (Tainted Heart...,Ayla\nThe darkness never truly left me. It's a...,"{'Romance': 38, 'Dark': 37, 'Sociology-Abuse':...",<NA>,4.64,408,87,,...,0.000000,0.000000,0.000000,0.413043,0.0,0.000000,0.000000,0.0,0.0,0.586957
43308,36421066,David Anderson,The Remnant,"Will, Kevin, Rose, Quentin and Fiona have over...",{'Science Fiction Fantasy': 1},<NA>,5.00,2,1,BWL Publishing Inc.,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,1.000000
43309,36430456,Elaine Williams Crockett,Do Not Ask,The President's beautiful twin daughters disap...,"{'Fiction': 4, 'Mystery': 3, 'Thriller': 2}",<NA>,5.00,3,3,BookBaby,...,0.444444,0.000000,0.000000,0.000000,0.0,0.000000,0.333333,0.0,0.0,0.222222
43310,36515426,Logan Chance,Heartbreaker,They call me a heartbreaker.\nI've constructed...,"{'Romance': 20, 'Contemporary': 6}",<NA>,4.48,185,49,,...,0.000000,0.000000,0.000000,0.769231,0.0,0.000000,0.000000,0.0,0.0,0.230769
43311,36524503,Emily Lloyd-Jones,The Bone Houses,A historical horror-fairy tale that follows a ...,"{'Fantasy': 841, 'Young Adult': 437, 'Horror':...",<NA>,2.00,1,1,"Little, Brown Books for Young Readers",...,0.000000,0.000000,0.243726,0.000000,0.0,0.088678,0.000000,0.0,0.0,0.198550

In [27]:
candidates_for_train = candidates_for_train.merge(items[['item_id', 'average_rating']], on = 'item_id', how = 'left')

In [28]:
candidates_to_rank = candidates_to_rank.merge(items[['item_id', 'average_rating']], on = 'item_id', how = 'left')

In [29]:
from catboost import CatBoostClassifier, Pool

# задаём имена колонок признаков и таргета
features = ['als_score', 'cnt_score', 
    'age', 'average_rating', 'rating_avg', 'reading_years', 'books_read', 
     'rating_std', 
    'books_per_year'] + genre_columns
target = 'target'

# создаём Pool
train_data = Pool(
    data=candidates_for_train[features], 
    label=candidates_for_train[target])

# инициализируем модель CatBoostClassifier
cb_model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.1,
    depth=6,
    loss_function='Logloss',
    verbose=100,
    random_seed=0,
)

# тренируем модель
cb_model.fit(train_data)

0:	learn: 0.6467431	total: 60.9ms	remaining: 1m
100:	learn: 0.4659972	total: 3.24s	remaining: 28.8s
200:	learn: 0.4575262	total: 7.12s	remaining: 28.3s
300:	learn: 0.4517715	total: 10.7s	remaining: 25s
400:	learn: 0.4470910	total: 15.2s	remaining: 22.8s
500:	learn: 0.4428447	total: 19.8s	remaining: 19.8s
600:	learn: 0.4387115	total: 22.8s	remaining: 15.1s
700:	learn: 0.4350553	total: 25.8s	remaining: 11s
800:	learn: 0.4317133	total: 29.2s	remaining: 7.26s
900:	learn: 0.4283640	total: 33.4s	remaining: 3.67s
999:	learn: 0.4252080	total: 36.7s	remaining: 0us

In [30]:
inference_data = Pool(data=candidates_to_rank[features])
predictions = cb_model.predict_proba(inference_data)

candidates_to_rank["cb_score"] = predictions

# для каждого пользователя проставим rank, начиная с 1 — это максимальный cb_score
candidates_to_rank = candidates_to_rank.sort_values(["user_id", "cb_score"], ascending=[True, False])
candidates_to_rank["rank"] = candidates_to_rank.groupby('user_id').cumcount() + 1

max_recommendations_per_user = 100
final_recommendations = candidates_to_rank.query("rank <= @max_recommendations_per_user")

In [35]:
predictions

array([[0.72930903, 0.27069097],
       [0.02555194, 0.97444806],
       [0.03981434, 0.96018566],
       ...,
       [0.95649313, 0.04350687],
       [0.9482867 , 0.0517133 ],
       [0.96200689, 0.03799311]])

In [32]:

final_recommendations.to_parquet('final_recommendations_feat.parquet')

In [34]:
events_inference

,user_id,item_id,started_at,read_at,is_read,rating,is_reviewed,started_at_month,user_id_enc,item_id_enc,target
278,1001879,3227063,2015-12-27,2016-01-10,True,4,True,2015-12-01,1879,21498,NaN
279,1001879,6483360,2016-02-03,2016-08-18,True,4,False,2016-02-01,1879,24085,NaN
280,1001879,9593913,2015-03-22,2015-03-30,True,3,True,2015-03-01,1879,27834,NaN
281,1001879,8525590,2014-12-31,2014-12-31,True,2,False,2014-12-01,1879,26976,NaN
282,1001879,15826934,2014-12-31,2014-12-31,True,4,False,2014-12-01,1879,33237,NaN
...,...,...,...,...,...,...,...,...,...,...,...
12910623,1026741,29056083,2017-08-07,2017-08-29,True,2,False,2017-08-01,26741,41809,1.0
12910624,1026741,43615,2017-08-07,2017-08-29,True,3,False,2017-08-01,26741,4072,1.0
12913151,1240985,21411887,2017-08-29,2017-08-30,True,5,False,2017-08-01,240985,38170,1.0
12913601,1211969,28763485,2017-09-14,2017-09-20,True,4,False,2017-09-01,211969,41746,1.0
12913602,1211969,18693763,2017-08-15,2017-08-23,True,4,False,2017-08-01,211969,36939,1.0

In [38]:
events_test_2

,user_id,item_id,started_at,read_at,is_read,rating,is_reviewed,started_at_month,user_id_enc,item_id_enc,gt
270,1001879,13206828,2017-09-24,2017-09-28,True,5,True,2017-09-01,1879,31274,True
271,1001879,13206900,2017-09-28,2017-10-07,True,4,True,2017-09-01,1879,31275,True
272,1001879,13206760,2017-09-21,2017-09-24,True,5,True,2017-09-01,1879,31273,True
276,1001879,23174274,2017-10-16,2017-10-21,True,3,False,2017-10-01,1879,39391,True
277,1001879,22328546,2017-10-10,2017-10-16,True,4,False,2017-10-01,1879,38704,True
...,...,...,...,...,...,...,...,...,...,...,...
12913232,1035481,136251,2017-10-21,2017-10-21,True,5,False,2017-10-01,35481,8250,True
12913557,1050964,10664113,2017-09-27,2017-10-02,True,5,False,2017-09-01,50964,28866,True
12913600,1211969,27883214,2017-10-12,2017-10-19,True,1,False,2017-10-01,211969,41514,True
12913611,1211969,1618,2017-10-09,2017-10-12,True,2,False,2017-10-01,211969,187,True
12913612,1211969,693208,2017-09-28,2017-10-09,True,5,False,2017-09-01,211969,15494,True

In [33]:
# для экономии ресурсов оставим события только тех пользователей, 
# для которых следует оценить рекомендации
events_inference = pd.concat([events_train, events_labels])
events_inference = events_inference[events_inference["user_id"].isin(events_test_2["user_id"].drop_duplicates())]

cb_events_recs_for_binary_metrics_5 = process_events_recs_for_binary_metrics(
    events_inference,
    events_test_2,
    final_recommendations.rename(columns={"cb_score": "score"}), 
    top_k=5)

cb_precision_5, cb_recall_5 = compute_cls_metrics(cb_events_recs_for_binary_metrics_5)

print(f"precision: {cb_precision_5:.3f}, recall: {cb_recall_5:.3f}")

Common users: 75194
precision: 0.000, recall: 0.000

In [39]:
feature_importance = pd.DataFrame(cb_model.get_feature_importance(), 
    index=features, 
    columns=["fi"])
feature_importance = feature_importance.sort_values('fi', ascending = False)

print(feature_importance )

                       fi
als_score       28.350608
age             18.725065
average_rating  14.200163
books_read       6.438743
cnt_score        3.755911
reading_years    2.947100
genre_18         2.734612
genre_1          2.595948
genre_others     2.394701
genre_25         2.256985
books_per_year   2.102880
genre_34         2.099150
genre_20         1.623277
genre_33         1.606765
genre_16         1.577645
genre_38         1.552854
genre_24         1.499920
rating_avg       1.425372
rating_std       1.075337
genre_5          1.036964

In [ ]:
1353637

In [2]:
rec = pd.read_parquet('final_recommendations_feat.parquet')

In [4]:
rec[rec['user_id'] == 1353637]

,user_id,item_id,als_score,cnt_score,cb_score,rank,age,reading_years,books_read,rating_avg,...,genre_38,genre_18,genre_34,genre_5,genre_16,genre_20,genre_24,genre_33,genre_others,average_rating
11913252,1353637,771620,NaN,0.837473,0.991313,1,83.0,5.275838,88.0,3.431818,...,0.076,0.046924,0.004938,0.07673,0.011986,0.028172,0.089333,0.003155,0.335474,3.73
11913279,1353637,182465,NaN,0.842259,0.988964,2,32.0,5.275838,88.0,3.431818,...,0.076,0.046924,0.004938,0.07673,0.011986,0.028172,0.089333,0.003155,0.335474,3.28
11913201,1353637,23937,NaN,0.859495,0.988198,3,24.0,5.275838,88.0,3.431818,...,0.076,0.046924,0.004938,0.07673,0.011986,0.028172,0.089333,0.003155,0.335474,3.45
11913246,1353637,516570,NaN,0.839391,0.981568,4,18.0,5.275838,88.0,3.431818,...,0.076,0.046924,0.004938,0.07673,0.011986,0.028172,0.089333,0.003155,0.335474,3.31
11913227,1353637,372392,NaN,0.840787,0.981086,5,37.0,5.275838,88.0,3.431818,...,0.076,0.046924,0.004938,0.07673,0.011986,0.028172,0.089333,0.003155,0.335474,3.71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11913185,1353637,13503109,0.298037,NaN,0.799323,96,6.0,5.275838,88.0,3.431818,...,0.076,0.046924,0.004938,0.07673,0.011986,0.028172,0.089333,0.003155,0.335474,3.75
11913144,1353637,15241,0.333188,NaN,0.786356,97,NaN,5.275838,88.0,3.431818,...,0.076,0.046924,0.004938,0.07673,0.011986,0.028172,0.089333,0.003155,0.335474,4.42
11913167,1353637,10357575,0.288311,0.834753,0.786297,98,7.0,5.275838,88.0,3.431818,...,0.076,0.046924,0.004938,0.07673,0.011986,0.028172,0.089333,0.003155,0.335474,3.89
11913162,1353637,18512,0.304692,NaN,0.785182,99,32.0,5.275838,88.0,3.431818,...,0.076,0.046924,0.004938,0.07673,0.011986,0.028172,0.089333,0.003155,0.335474,4.51
11913134,1353637,13538873,0.357491,NaN,0.782187,100,6.0,5.275838,88.0,3.431818,...,0.076,0.046924,0.004938,0.07673,0.011986,0.028172,0.089333,0.003155,0.335474,3.75